package main

import (
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"github.com/tengkuroman/microshop/docs/swagger" // docs is generated by Swag CLI, you have to import it.
)

// @contact.name   Tengku Romansyah
// @contact.url    https://linkedin.com/in/tengkuroman
// @contact.email  tengku.romansyah@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @securityDefinitions.apikey BearerToken
// @in header
// @name Authorization

func main() {
	// programmatically set swagger info
	swagger.SwaggerInfo.Title = "Microshop API Documentation"
	swagger.SwaggerInfo.Description = "This is a documentation to access all endpoints on Microshop's microservices."
	swagger.SwaggerInfo.Version = "1.0"
	swagger.SwaggerInfo.Host = "localhost:8000"
	swagger.SwaggerInfo.BasePath = "/api"
	swagger.SwaggerInfo.Schemes = []string{"http", "https"}

	r := gin.Default()

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run()
}
